finnishtransportagency/raita

.gitignore
.npmignore
bin/parsing-test.ts
cdk.json
jest.config.js
lambda/adapters/openSearchRepository.ts
lambda/adapters/s3ConfigRepository.ts
lambda/adapters/s3FileRepository.ts
lambda/config/index.ts
lambda/mermecParser/contentDataParser.ts
lambda/mermecParser/fileNameDataParser.ts
lambda/mermecParser/mermecParser.ts
lambda/mermecParser/pathDataParser.ts
lambda/ports/backend.ts
lambda/ports/configPort.ts
lambda/ports/metadataPort.ts
lambda/types/index.ts
lambda/types/portDataStorage.ts
lambda/types/portFile.ts
lambda/types/portSpecification.ts
lambda/types/specification.ts
lambda/utils/logger.ts
lambda/utils/regex.ts
lib/raita-stack.ts
package-lock.json
package.json
tsconfig.json

Base parser and infrastructure implementation, infrastucture set up by cdk requires some OpenSearch related hands on configuration to work

feat: RAITA-15 Infrastructure and parser base

---

package-lock.json
package.json

Update aws-cdk to fix mismatch between CDK CLI and library

chore: Update aws-cdk

---

README.md
package-lock.json
package.json

There were extra cd in them
Updated pipeline README to mention bootstrapping
Made cross-env a devDependency instead of dependency

chore: RAITA-18 Fixed pipeline scripts

---

backend/adapters/openSearchRepository.ts
backend/lambdas/handleFileRequest/handleFileRequest.ts
backend/lambdas/handleOpenSearchQuery/handleOpenSearchQuery.ts
backend/lambdas/utils.ts
backend/ports/metadataPort.ts
backend/types/portDataStorage.ts
lib/raita-gateway.ts
lib/raita-stack.ts

Adds a DRAFT API endpoint that queries OpenSearch based on OpenSearch query included in request.
Includes refactoring of lambda response error handling.

Feature/RAITA-90 Opensearch query endpoint

---

lib/raita-cloudfront.ts

Adds domain name and certificate to Cloudfront. Also sets Cloudfront priceclass to 100.

Feature/RAITA-140 Domain name and certificate to Cloudfront

---

lib/raita-api.ts
lib/raita-stack.ts

Pull request renames api gateway handler lambdas removing naming conflict with existing deployed stack.

Fix/RAITA-115 Resource placement in vpc part 2

---

lib/raita-frontend.ts
lib/utils.ts

Fixes potential deploy naming conflict regarding frontend bucket in stack reorganization. Also small update to getRemovalPolicy helper (use of string literal removed).

fix(stack): RAITA-143 add data reception bucket fe bucket name conflict

---

lib/raita-stack.ts

Pull request fixes incorrect vpc identifier.

fix(vpc): RAITA-154 correct vpc identifier

---

frontend/components/__tests__/__snapshots__/pager.tsx.snap
frontend/components/__tests__/pager.tsx
frontend/components/pager.tsx
frontend/pages/reports/index.tsx
frontend/public/locales/en/common.json
frontend/public/locales/en/metadata.json
frontend/shared/config.ts
frontend/shared/hooks.ts

Fixes a couple of invalid states from the pager. Also adds a11y semantics to its elements, and implementation for the Reports view.

fix: Pager

---

constants/index.ts
lib/config.ts
lib/raita-application.ts
lib/raita-data-process.ts
lib/raita-stack.ts

infra: RAITA-160 Added sftp bucket policy

---

lib/raita-application.ts

Pull request enables OpenSearch in-place version upgrade feature (data base upgrade to follow in a subsequent pull request).

infra: RAITA-179 enable os version upgrade

---

lib/raita-application.ts

Pull request updates OpenSearch version to 1.3 in place (in feature branch data was not affected by upgrade).

infra:RAITA-179 opensearch version upgrade to 1.3

---

lib/raita-application.ts
lib/raita-stack.ts

Fix for incorrect argument preventing bastion stack creation.

fix: RAITA-194 bastion stack creation condition argument

---

backend/lambdas/dataProcess/handleInspectionFileEvent/contentDataParser.ts
backend/lambdas/dataProcess/handleInspectionFileEvent/fileNameDataParser.ts
backend/lambdas/dataProcess/handleInspectionFileEvent/handleInspectionFileEvent.ts
backend/lambdas/dataProcess/handleInspectionFileEvent/parsePrimitives.ts
backend/lambdas/dataProcess/handleInspectionFileEvent/pathDataParser.ts
backend/lambdas/dataProcess/handleReceptionFileEvent/handleReceptionFileEvent.ts
backend/lambdas/raitaApi/handleFileRequest/handleFileRequest.ts
backend/lambdas/raitaApi/handleFilesRequest/handleFilesRequest.ts
backend/lambdas/raitaApi/handleImagesRequest/handleImagesRequest.ts
backend/lambdas/raitaApi/handleMetaRequest/handleMetaRequest.ts
backend/utils/logger.ts
backend/utils/userService.ts
backend/utils/validateJwtToken.ts
lib/raita-api.ts
package-lock.json
package.json

Authorise API calls
Log API calls and errors
Some other logs as well here and there
Added relevant new dependencies
Added log retention to lambdas

feat: RAITA-149, RAITA-218 Add authorisation and logging

---

backend/utils/userService.ts
constants/index.ts
lib/config.ts
lib/raita-api.ts
lib/raita-application.ts
lib/raita-stack.ts

Also check that env are there in getUser

fix: RAITA-218 Added missing env variables

---

backend/utils/validateJwtToken.ts

Use require instead for some reason

fix: RAITA-218 Import jwktopem differently

---

backend/lambdas/cloudfront/frontendRedirect/handleFrontendRedirect.js
backend/lambdas/raitaApi/handleReturnLogin/handleReturnLogin.ts
backend/utils/validateJwtToken.ts
lib/raita-api.ts
lib/raita-application.ts
lib/raita-cloudfront.ts
lib/raita-stack.ts

To make sure that user has a valid SSO session by going to the backend
Also added allowed methods and caching to default behavior
Redirect to reports.html by default now

feat: RAITA-226 Added initial frontend redirect SSO check

---

lib/raita-application.ts

Pull request adds bastion host to production stack.

infra: RAITA-248 add production bastion host

---

README.md
lib/config.ts

docs: Updated README with pipeline deployment instructions

chore: Added missing VPC resources for prod

---

lib/raita-cloudfront.ts

Reverts finnishtransportagency/raita#89

Revert "feat: Disable certificate for prod temporarily"

---

lib/raita-application.ts

Pull request adds a resource based policy to OpenSearch that grands all users access to all endpoints to the os domain. Additionally, bastion host service role os permissions are removed (for clarity, not used currently).

infra: RAITA-272 add os wildcard resource based policy

---

frontend/package-lock.json
frontend/package.json
frontend/pages/reports/index.tsx
frontend/public/locales/en/common.json
frontend/public/locales/fi/common.json
frontend/shared/hooks.ts
frontend/shared/rest.ts
frontend/shared/types.ts

Funtionality to fetch and show images associated

---

frontend/components/textinput/index.tsx
frontend/pages/reports/index.tsx
frontend/public/locales/en/common.json
frontend/public/locales/fi/common.json
frontend/shared/query-builder.ts

New text input to use for searching documents by filename

feat: RAITA-276 free text search

---

backend/adapters/openSearch/openSearchResponseParser.ts

fix: RAITA-200 download all as zip

---

frontend/components/footer.tsx
frontend/components/infobanner.tsx
frontend/components/loading-overlay.module.css
frontend/components/loading-overlay.tsx
frontend/pages/reports/index.tsx
frontend/public/locales/en/common.json
frontend/public/locales/fi/common.json

New loading screen with contact information on fault- or access management related issues. New info banner showing the restrictions of the data being used.

feat: RAITA-278 Add instructions to UI

---

backend/lambdas/raitaApi/handleZipRequest/handleZipProcessing.ts
backend/lambdas/raitaApi/handleZipRequest/handleZipRequest.ts
backend/lambdas/raitaApi/handleZipRequest/utils.ts
frontend/components/zip-download.tsx
lib/raita-api.ts
lib/raita-application.ts
package-lock.json
package.json

Call the zip processing lambda with another lambda, to get
asynchronous functionality.

Fix: RAITA-200 Use another lambda to invoke the zipping process

---

backend/lambdas/raitaApi/handleZipRequest/handleZipProcessing.ts
backend/lambdas/raitaApi/handleZipRequest/handleZipRequest.ts
backend/lambdas/raitaApi/handleZipRequest/utils.ts
frontend/components/zip-download.tsx
lib/raita-api.ts
lib/raita-application.ts
package-lock.json
package.json

Reverts finnishtransportagency/raita#120

Revert "Revert "Fix: RAITA-200 Use another lambda to invoke the zipping process""

---

backend/lambdas/raitaApi/handleZipRequest/handleZipProcessing.ts
backend/lambdas/raitaApi/handleZipRequest/handleZipRequest.ts
backend/lambdas/raitaApi/handleZipRequest/utils.ts
frontend/components/zip-download.tsx
lib/raita-api.ts
lib/raita-application.ts
package-lock.json
package.json

Call the zip processing lambda with another lambda, to get asynchronous functionality.
* Modified the ALB rule priority due to cloudformation errors.
* New role and policy for zipRequest lambda to be able to invoke the zipProcess lambda
*  removed console.logs

fix: RAITA-200 Trigger zip process with lambda

---

backend/lambdas/raitaApi/handleZipRequest/handleZipProcessing.ts
frontend/components/zip-download.tsx
frontend/pages/reports/index.tsx

The lambda will stop execution when the amount or size of files grows too big. At this point we will limit the size, until come up with a more robust solution

fix: RAITA-200 limit zip size

---

lib/raita-application.ts

The RaitaApiLambdaServiceRole that is responsible of dealing with the API-related lambdas, lacked the permission to fetch the API key parameter from parameter store. Created a policy to give the role sufficient permissions.

fix: RAITA-285 API-Lambda insuccifient permissions

---

lib/raita-api.ts

Opened all of the endpoints as an external endpoint aswell.

feat: All external endpoints

---

frontend/components/daterange.tsx

Made the ending date of the daterange to be inclusive

fix: RAITA-284 daterange bug

---

frontend/components/daterange.tsx
frontend/components/filters/selector.tsx
frontend/components/textinput/index.tsx
frontend/pages/reports/index.tsx

Clear also the daterange, filter selector and text search filters

fix: RAITA-281 Clear all filters

---

frontend/components/infobanner.tsx
frontend/components/spinner.tsx
frontend/pages/reports/index.tsx
frontend/public/locales/en/common.json
frontend/public/locales/fi/common.json
frontend/shared/types.ts

Opensearch only returns maximum of 10k results by default. Show user a banner to limit their search if they get too many results. Also fixed the size problem of the spinner animation.

feat: RAITA-282 Notice user if over 10k results

---

frontend/pages/reports/index.tsx
frontend/public/locales/en/metadata.json
frontend/public/locales/fi/metadata.json

Translations for the system name abbreviations

feature: RAITA-291 Naming of systems

---

backend/containers/zipHandler/src/index.ts

Changed the log level to info, to always receive logging from the extraction process.

feature: RAITA-293 Log zip process

---

constants/index.ts
lib/config.ts
lib/raita-application.ts
lib/raita-data-process.ts
lib/raita-stack.ts

* Bucket policies to let SOA-offices "väylä" and "loram" roles to access Data Reception Bucket in S3

Main -> Prod 28.6.2023

---

README.md
frontend/README.md
frontend/pages/api/file.ts

Update README file and remove a hardcoded test file path.

RAITA-302 update dev documentation

---

frontend/components/daterange.tsx

End date input field now selects correct date

RAITA-284: Fix behaviour of end date input field

---

lib/raita-cloudfront.ts
lib/raita-stack.ts

Revert ssm param fix that did not work
This reverts commit 21ef5faec879a2a9c148d796f5fe43c6454892ba.

Revert "try fixing cloudfront cert parameter (#168)"

---

frontend/components/button/button.module.css
frontend/pages/graphql_reports/index.tsx
frontend/shared/doc/manual.md

Paging buttons to show how many results in single page. Minor fixes to instruction modal.

Paging button to change color on click and minor add to instructions

---

frontend/components/results-pager.tsx
frontend/pages/graphql_reports/index.tsx
frontend/public/locales/fi/common.json

Changed navigation layout for more neat look. Added button to be visible whenever exact page is given. Button works as trigger for submitting.

Changes to page navigation

---

frontend/components/button/button.module.css
frontend/components/button/index.tsx
frontend/components/header/index.tsx
frontend/components/pollingHandler.tsx
frontend/components/zip-download-graphql.tsx
frontend/pages/_app.tsx
frontend/pages/graphql_reports/index.tsx
frontend/shared/util.ts
frontend/shared/zipContext.ts

Zip and download to work whether user leaves the page. Downloading is possible only from the reports page. User can leave the reports page, but the process goes to "pause mode" when other page. After Zip is done the download is possible until application is refreshed.

Zip and download button fixes

---

frontend/pages/graphql_reports/index.tsx

fix to disappeared pager

---

backend/apollo/utils.ts
backend/lambdas/raitaApi/csvGeneration/handleCsvGeneration.ts
backend/lambdas/raitaApi/csvGeneration/utils.ts
frontend/pages/csv/index.tsx

RAITA-658-csv-output-complete-fixes

---

backend/lambdas/dataProcess/csvCommon/db/converters/dataConverters.ts
backend/lambdas/dataProcess/csvCommon/db/dbUtil.ts
backend/lambdas/dataProcess/handleCSVFileEvent/csvDataParser/csvDataParser.ts
lib/raita-data-process.ts

Postgres raw queries to prisma requests. Also added type checking and conversions to dataconverters.ts

Fix/raita 521 

---

backend/apollo/schemas/mittaus.graphql

RAITA-655/fix to non nullable return value

---

frontend/public/locales/fi/common.json

RAITA-677/csv-name-label

---

backend/lambdas/conversionProcess/handleGeoviiteConversionProcess/handleGeoviiteConversionProcess.ts
backend/lambdas/conversionProcess/handleStartConversionProcess/handleStartConversionProcess.ts
backend/lambdas/conversionProcess/util.ts
backend/lambdas/geoviite/geoviiteClient.ts

…es in smaller parts to handle properly

RAITA-682: enable converting whole files via geoviite converter

---

backend/utils/adminLog/pgLogReader.ts
backend/utils/adminLog/types.ts
package-lock.json
package.json

Logs supposed to be grouped by log date and key values.

adminlog fixes to logSummary

---

backend/lambdas/dataProcess/csvCommon/db/dbUtil.ts

Removed postgres imports and some getconnection functions that are unused.

Removing unused postgres imports

---

backend/lambdas/raitaApi/csvGeneration/__tests__/utils.test.ts
backend/lambdas/raitaApi/csvGeneration/handleCsvGeneration.ts
backend/lambdas/raitaApi/csvGeneration/utils.ts
frontend/pages/csv/index.tsx
frontend/public/locales/fi/common.json
frontend/shared/doc/manual.md
lib/raita-application.ts

- Csv title changed
- Changed csv-titles
- Changed search parameters from "geoviite" to "Viitekehysmuunnin korjattu"
- Fixed tests
- Added user manual

Raita 701 csv page changes

---

backend/lambdas/raitaApi/handleManualDataProcessRequest/handleManualDataProcessRequest.ts

Fix to over 100mb file manual data processing. Added metadata

RAITA-699/metadata-fixes-to-multipart

---

backend/lambdas/raitaApi/csvGeneration/handleCsvGeneration.ts

Added BOM to the beginning of csv stream. Should work fine.

RAITA-711/csv-column-name-fix
