finnishtransportagency/raita

- lambda/adapters/openSearchRepository.ts
- lambda/mermecParser/contentDataParser.ts
- lambda/mermecParser/fileNameDataParser.ts
- lambda/mermecParser/pathDataParser.ts
- lambda/types/index.ts
- lambda/types/specification.ts
- lambda/utils/logger.ts
- lambda/utils/parsePrimitives.ts
- lambda/utils/regex.ts
- package-lock.json
- package.json
Introduces bare-bones data type parsing to parser to get data types correctly in the data base. The Open Search now relies on [dynamic mapping](https://opensearch.org/docs/1.3/opensearch/mappings/#dynamic-mapping) to set index field types. In extractionSpec each item can have optional parseAs property with possible values of integer, float, date.
This is not yet a fully-fledged solution (especially date parsing needs more consideration).
Sorry for the single quotes/double quotes mess.
> Feat: RAITA-52 Parse field data types for OpenSearch

- lambda/s3urlGenerator/s3UrlGenerator.ts
- lib/raita-gateway.ts
- lib/raita-stack.ts
Base implementation for generating pre-signed urls (introducing Api Gateway and url generating lambda). Enables a Cognito user to get a pre-signed url to a S3 file.
Removal policy for stateful resources (S3 buckets, OpenSearch domain and User pool) has been set to DESTROY (previously this was set only for S3 buckets).
> Feature: RAITA-53 S3 file access via cognito auth

- lib/raita-stack.ts
Pull request changes the raita open search domain name to deploy new instance into vpc (and to remove old non-vpc instance).
> fix/RAITA-155 Change os name to init fresh vpc os

- lib/raita-cloudfront.ts
Temporarily rename frontend bucket to enable refactoring stack structure from branch feature/RAITA-141-pipeline-build-and-deploy-frontend
> refactor: RAITA-145 rename frontend bucket

- lib/raita-api.ts
Resolves alb resource naming conflict by slightly changing the resource name.
>  fix(stack): RAITA-143 add data reception bucket alb name conflict

- lib/raita-stack.ts
Returns ApplicationStack resources to aws account infra, now using the vpc that pre exists in the account. 
Additional small cleanup: raitaStackIdentifier is not places as a class member variable anymore in the top level RaitaStack.
> refactor(infra): RAITA-154 enable use of existing vpc

- lib/raita-api.ts
- lib/raita-application.ts
Temporarily removes OpenSearch and dependent resources from AWS infra to enable creation of application load balancer within vpc (to bypass error "Exceeded attemps to wait" originating from os).
> refactor: RAITA-154 temporary open search and dependent resource removal

- lib/raita-api.ts
- lib/raita-application.ts
- lib/raita-data-process.ts
In this sequel to RAITA-154 saga OpenSearch and dependent resources return (hopefully) to the company of other AWS infra resources.
Additionally small clean-ups: Removal of unused import from raita-data-process.ts, removal of unnecessary class member variable from raita-application.ts
> refactor: RAITA-154 return of open search and dependent components

- frontend/next.config.js
- frontend/pages/reports/index.tsx
- frontend/shared/config.ts
- frontend/shared/hooks.ts
- frontend/shared/rest.ts
- frontend/shared/types.ts
- Updated typedefs for ElasticSearch result documents
- Use correct `key` and `file_name` for requesting signed file URLs
- Disable optimizations temporarily to allow for convenient debugging on deployed software (minification off, `console.*` calls are not removed)
> fix: buxfixes for demo

- backend/adapters/openSearch/openSearchRepository.ts
- backend/adapters/openSearch/openSearchResponseParser.ts
- backend/adapters/openSearch/openSearchResponseSchemas.ts
- backend/types/portDataStorage.ts
- backend/types/portFile.ts
Adds three new new fields to meta endpoint response: 
- systems
- trackNumbers
- trackParts
This pull request in current form is non-breaking but leaves improvement to response structure. The three below small breaking modifications would make the endpoint cleaner:
- Added new fields list return a list of values in generic format {value: "some_value", count:2 } where as already existing aggregations (reportType, fileType) instead of value a specific field name is used  {reportType: "some_value", count:2 }. It would be better to return all in format {value: "some_value", count:2 }
- fields property structure is cumbersome [{campaign:{type:text}] and could be replaced with simpler [{value: campaign, type:text}]
- filter options data would be best nested under some common property such as …
> Feat: RAITA-186 meta endpoint new fields

- backend/adapters/s3FileRepository.ts
- backend/containers/zipHandler/package-lock.json
- backend/containers/zipHandler/package.json
- backend/containers/zipHandler/src/constants.ts
- backend/containers/zipHandler/src/index.ts
- backend/containers/zipHandler/src/logger.ts
- backend/containers/zipHandler/src/processZipFile.ts
- backend/containers/zipHandler/src/types.ts
- backend/containers/zipHandler/src/utils.ts
- backend/lambdas/dataProcess/handleInspectionFileEvent/contentDataParser.ts
- backend/lambdas/dataProcess/handleInspectionFileEvent/fileNameDataParser.ts
- backend/lambdas/dataProcess/handleInspectionFileEvent/handleInspectionFileEvent.ts
- backend/lambdas/dataProcess/handleInspectionFileEvent/pathDataParser.ts
- backend/lambdas/dataProcess/handleReceptionFileEvent/handleReceptionFileEvent.ts
- backend/lambdas/utils.ts
- backend/types/index.ts
- backend/types/specification.ts
- backend/utils/logger.ts
- constants/index.ts
- lib/config.ts
This pull request is a collection of updates and fixes:
- rename os index 'metadata-index' to 'metadata'
- Ignore video-files in zip-extraction
- RAITA-208 Fix copying non zip files from reception bucket to data bucket
- zip-file name addition to extracted file key
- zip name and zip date added into extracted file tags (and additionally to meta data entry)
- fix for excel file name meta data parsing
- zipHandler container to use new logging solution
> fix: RAITA-8 collection of updates and fixes

- backend/lambdas/dataProcess/handleReceptionFileEvent/handleReceptionFileEvent.ts
- lib/raita-data-process.ts
- lib/raitaResourceCreators.ts
Pull request fixes problem with sftp partial/temp files in data reception bucket.
- Reception bucket files are versioned
- Delete permission for sftp user
- Only excel files are copied directly to destination data bucket (not all non-zip files). This probably needs to be modified at some later point when more is known (Jira issue exists for doc file).
Jira 232 created for temp file permanent deletion from reception bucket.
Untested, must be tested in main-stack.
> fix: RAITA-228 sftp partial files

- backend/adapters/openSearch/openSearchRepository.ts
- backend/adapters/openSearch/openSearchResponseParser.ts
- backend/adapters/openSearch/openSearchResponseSchemas.ts
- frontend/pages/reports/index.tsx
- frontend/shared/hooks.ts
- frontend/shared/types.ts
- lib/raita-data-process.ts
Pull request modifies meta-endpoint to return only data required by frontend (and other potential api users).
Not tested in feature branch due to Jira 252 (feature endpoint calls to db fail due missing permissions).
Also includes an unrelated chance: adds removalPolicy to Raita ECR container registry (otherwise repos are left hanging after stack removal)
> fix(api): RAITA-224 cleanup files endpoint response

- backend/lambdas/dataProcess/handleInspectionFileEvent/handleInspectionFileEvent.ts
- backend/lambdas/dataProcess/handleReceptionFileEvent/handleReceptionFileEvent.ts
- backend/lambdas/raitaApi/handleImagesRequest/handleImagesRequest.ts
- backend/lambdas/utils.ts
- lib/raita-api.ts
Pull request fixes download bug concerning files with keys that contain scandic letters:  the whole file key is now url decoded before it is stored in to the database (previously only file name was url decoded).
Additionally, pull request addresses bug in RAITA-252 by granting POST permissions to api service role to metadata index.
> fix: RAITA-262 download file with key containing scandic letters

- backend/adapters/openSearch/openSearchRepository.ts
Fixed the wrong condition that allowed the execution to go forward even if we went to addDoc.
> fix: Raita-34 fix upsertDocument

- lib/raita-api.ts
Due to copypaste, the lamba had a wrong entry path
> fix: RAITA:200 Correct path to lambda

- backend/lambdas/raitaApi/handlePollingRequest/handlePollingRequest.ts
In most lambdas we use the older s3 api in s3 operations, which has more straight forward way to handle with files. Refactored pollinglambda also to use the older api, to be able to parse the file content.
> fix: RAITA-200 Use S3 instead of S3client

- frontend/components/filters/multi-choice.tsx
- frontend/pages/reports/index.tsx
When the user clicked the clear-button of the multiselects, we did clear the filters from the query, but it 
still looked like the filters were selected on the UI.
Now when clicked, we set all the filters to 'No choice'
> fix: RAITA-281 UI clear filters

- backend/lambdas/raitaApi/handleZipRequest/handleZipProcessing.ts
- backend/lambdas/raitaApi/handleZipRequest/utils.ts
- frontend/components/zip-download.tsx
Current functionality only allows to compress files up to 15mb, or in total 500 files. The problem might relate to stream timeouting on bigger objects as explained here https://gist.github.com/amiantos/16bacc9ed742c91151fcf1a41012445e
)
Modified the original implementation according the typescript example on the link
> fix: RAITA-283 Dowload as zip

- README.md
- backend/lambdas/raitaApi/handleZipRequest/handleZipProcessing.ts
- backend/lambdas/raitaApi/handleZipRequest/handleZipRequest.ts
- backend/lambdas/raitaApi/handleZipRequest/utils.ts
- frontend/components/daterange.tsx
- frontend/components/zip-download.tsx
- frontend/pages/reports/index.tsx
- frontend/public/locales/en/common.json
- frontend/public/locales/fi/common.json
- lib/raita-api.ts
Fine tuning for the zipping functionality, changed the size restriction of the files to be zipped to 5GB instead of 15mb. Removed unnecessary async from createLazyDownloadStreamFrom function, updated documentation concerning the change of github token in secrets manager
> fix: RAITA-283 Download as zip 2

- constants/index.ts
- lib/config.ts
- lib/raita-application.ts
- lib/raita-data-process.ts
- lib/raita-stack.ts
New bucket policies to allow SOA offices väylä and loram roles to do operations on the data
reception bucket. Also refactored the policy creation functionality
> feat: SOA Office bucket policies

- frontend/middleware.ts
- frontend/shared/config.ts
Add a middleware for redirecting api requests to bastion pipe locally.
The middleware is not used in production, so this only affects the local dev environment
> RAITA-319 Add workaround for using api locally

- frontend/components/filters/__tests__/multi-choice.tsx
- frontend/components/filters/multi-choice.tsx
- frontend/package-lock.json
- frontend/package.json
- frontend/pages/reports/index.tsx
- frontend/shared/__tests__/query-builder.ts
Change the report filtering elements from native select elements to custom element to allow searching the filter choices.
Added the react-select library to the project to accomplish this.
Also added a simple unit test.
https://github.com/finnishtransportagency/raita/pull/149 should be merged before this
Also added to this PR:
- Fix failing frontend test for query-builder by adding missing expected values. It seems the function was updated in commit 471bdd076c34eb7bb4717ee1a8131cd87a6ca882 but test was not updated
After this all frontend tests should be passing
> RAITA 316 Add search functionality to report filters

- frontend/shared/__tests__/query-builder.ts
- frontend/shared/query-builder.ts
In frontend: translate a inspecton_datetime metadata query to an OR query between inspection_datetime and inspection_date in the makeQuery function.
This is a (temporary?) solution for the problem where some files are missing the inspection_datetime field but they still have the inspection_date field. However it is possible that old data does not have the inspection_date field.
Added a unit test to test the query translation
> RAITA-306/RAITA-326 Fix for timestamp search 

- frontend/components/filters/__tests__/multi-choice.tsx
- frontend/components/filters/multi-choice.module.css
- frontend/components/filters/multi-choice.tsx
- frontend/package-lock.json
- frontend/package.json
- frontend/pages/reports/index.tsx
- frontend/public/locales/en/common.json
- frontend/public/locales/fi/common.json
- frontend/shared/__tests__/query-builder.ts
Revert changes from PR https://github.com/finnishtransportagency/raita/pull/150 that introduced react-select library and continue using the native select elements.
Add a text input to filter contents of the select elements.
> RAITA-316: Improvements to select element filtering

- backend/lambdas/__tests__/utils.test.ts
- backend/lambdas/dataProcess/handleInspectionFileEvent/__tests__/contentDataParser.test.ts
- backend/lambdas/dataProcess/handleInspectionFileEvent/__tests__/fileNameDataParser.test.ts
- backend/lambdas/dataProcess/handleInspectionFileEvent/__tests__/parseFileMetaData.test.ts
- backend/lambdas/dataProcess/handleInspectionFileEvent/__tests__/parsePrimitives.test.ts
- backend/lambdas/dataProcess/handleInspectionFileEvent/__tests__/pathDataParser.test.ts
- backend/lambdas/dataProcess/handleInspectionFileEvent/fileNameDataParser.ts
- backend/lambdas/dataProcess/handleInspectionFileEvent/handleInspectionFileEvent.ts
- backend/lambdas/dataProcess/handleInspectionFileEvent/parseFileMetadata.ts
- backend/utils/logger.ts
- frontend/jest.config.js
- jest.config.js
- lib/raita-pipeline.ts
Add unit tests for metadata parser and run them in the pipeline in a UnitTest step.
Some tests exist that have been explicitly skipped because they relate to bugs that need to be fixed.
> RAITA-323: Parser unit tests

- frontend/components/daterange.tsx
- frontend/pages/reports/index.tsx
Some fixes to the time range start/end datepicker inputs:
- The end date picker now uses 23:59 time instead of 00:00 so the whole day is covered
- Allow selecting same start and end date to select only results from one day
Also fix two bugs not originally in the scope of the ticket:
- Fix a javascript crash when inputing invalid or empty values in the datepicker
- When changing results page, make sure page number is updated in the query before refetching
> RAITA-284: Fixes to datepicker 

- backend/lambdas/dataProcess/handleInspectionFileEvent/fileNameDataParser.ts
- backend/lambdas/dataProcess/handleInspectionFileEvent/pathDataParser.ts
- backend/lambdas/utils.ts
- lib/raita-data-process.ts
- Add cloudwatch alarms that trigger when data process lambdas log errors
- Add some more detail about the type of error in "errorType" field for logged messages
> RAITA-329: first version of metadata parsing errors

- frontend/components/loading-overlay.tsx
- frontend/next-i18next.config.js
Add backup error message with noscript tags for when javascript fails.
Remove translation caching for now.
> RAITA-356 backup error message

- frontend/components/latest_inspection_date/index.tsx
Updated header row latest inspectiondate to use graphql queries.
> RAITA 545: Inspection date to gql

- backend/lambdas/dataProcess/handleInspectionFileEvent/__tests__/postgresRepository.test.ts
- backend/lambdas/dataProcess/handleInspectionFileEvent/handleInspectionFileEvent.ts
- backend/lambdas/utils.ts
If report is found, don't update parsed_at_datetime matadata. Instead use the one within the found report.
> RAITA-573: Don't update parsed_at_datetime

- frontend/components/header/index.tsx
- frontend/components/pollingHandler.tsx
- frontend/components/zip-download-graphql.tsx
- frontend/pages/graphql_reports/index.tsx
- frontend/public/locales/fi/common.json
- frontend/shared/config.ts
Download buttons now only in header row.
New search triggers former zip package to vanish.
Over 5GB and 4000kpl files not possible to download.
> Fixes to zip downloading-merge conflict

- frontend/components/log_accordion/index.tsx
Warning colors deleted from foldering fields in adminlogs.
Yellow: ("Sisältää virheitä"),
Red: ("Yhtään tiedostoa ei käsitelty")
> RAITA-664/adminlog warningsign deletions
